# Generated by Django 3.2.7 on 2021-10-14 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Articulo')),
                ('descripcion', models.TextField(max_length=200, verbose_name='Descripción del Articulo')),
                ('codigo', models.IntegerField(verbose_name='Codigo')),
                ('foto', models.ImageField(null=True, upload_to='Inventario', verbose_name='Agregar Imagen')),
            ],
            options={
                'verbose_name': 'Articulo a Inventariar',
                'verbose_name_plural': 'Articulos a Inventariar',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaIngreso', models.DateTimeField(verbose_name='Fecha y hora de ingreso')),
                ('reacondicinado', models.BooleanField(default=False, verbose_name='¿Es reacondicionado?')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.articulo', verbose_name='Seleccione el producto')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventario',
            },
        ),
    ]
