# Generated by Django 3.2.7 on 2021-10-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='code',
            field=models.IntegerField(verbose_name='Codigo'),
        ),
    ]
