# Generated by Django 3.2.7 on 2021-10-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_articulo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='avatar',
            field=models.ImageField(null=True, upload_to='imgArticulos', verbose_name='Agregar Imagen'),
        ),
    ]
