# Generated by Django 3.2.7 on 2021-10-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cliente_proveedor_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='phone',
            field=models.IntegerField(verbose_name='Número de Teléfono'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='numdocumento',
            field=models.IntegerField(verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='phone',
            field=models.IntegerField(verbose_name='Número de Teléfono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='phone',
            field=models.IntegerField(verbose_name='Número de Teléfono'),
        ),
    ]
